### ISSUE TITLE
Clear output from notebooks?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy4scipy2014#11]
I think we should have a script to automatically clear the output from the main notebooks, because when users open them up we want them to be able to run the inputs and see the outputs as they go.

**Comment by embray** [comment]
Good point.  I'll have to double check but I think that's easy to do.  I could add it to the notebooks Makefile.

**Comment by embray** [comment]
And if nothing else it'll be easy enough a little before the workshop to just open them all one by one, clear output, and save.

**Comment by astrofrog** [comment]
Added a script in bb10301304f75db606b4f76ddb77e06d4749713e
